language: generic
sudo: required
install: travis_wait mvn install
services:
  - docker

before_install:
  - docker build -t pravallikavasi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pravallikavasi/react-test npm test

after_success:
  - docker build -t pravallikavasi/multi-client ./client
  - docker build -t pravallikavasi/multi-nginx ./nginx
  - docker build -t pravallikavasi/multi-server ./server
  - docker build -t pravallikavasi/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push pravallikavasi/multi-client
  - docker push pravallikavasi/multi-nginx
  - docker push pravallikavasi/multi-server
  - docker push pravallikavasi/multi-worker